org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.21.1
minecraft_version_range=[1.20.1,1.21)

loom.platform=neoforge

forge_version=47.4.0
forge_version_range=[47,)
loader_version_range=[47,)

mod_id=jeiae2compact

mod_license=MIT
mod_version=0.0.1
mod_group_id=com.yshs

jei_version=19.21.2.313
ae2_version=19.2.12
